--- CONSTRAINTS TABLE T_ESTADO
    ALTER TABLE SYSCANVAS.T_ESTADO MODIFY (ESTPYTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_ESTADO MODIFY (CODFASE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_ESTADO MODIFY (CODNIVEL NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_ESTADO MODIFY (DESESTADO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_ESTADO ADD CONSTRAINT T_ESTADO_PK PRIMARY KEY (ESTPYTO, CODFASE, CODNIVEL)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_TIPO_DOC
    ALTER TABLE SYSCANVAS.T_TIPO_DOC MODIFY (TIPDOC NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TIPO_DOC MODIFY (DENDOC NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TIPO_DOC MODIFY (DENCORTA NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TIPO_DOC MODIFY (VIGENTE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TIPO_DOC ADD CONSTRAINT T_TIPO_DOC_PK PRIMARY KEY (TIPDOC)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_EMPLEADO
    ALTER TABLE SYSCANVAS.T_EMPLEADO MODIFY (CODPERS NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_EMPLEADO MODIFY (DIRECC NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_EMPLEADO MODIFY (HOBBY NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_EMPLEADO MODIFY (DNI NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_EMPLEADO MODIFY (NROCIP NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_EMPLEADO MODIFY (FECCIPVIG NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_EMPLEADO MODIFY (LICCOND NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_EMPLEADO MODIFY (CODCARGO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_EMPLEADO MODIFY (VIGENTE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_EMPLEADO ADD CONSTRAINT EMPLEADO_PK PRIMARY KEY (CODPERS)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_RESULCONV
    ALTER TABLE SYSCANVAS.T_RESULCONV MODIFY (NROCONV NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_RESULCONV MODIFY (CORRCONV NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_RESULCONV MODIFY (GANADOR NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_RESULCONV ADD CONSTRAINT T_RESULCONV_PK PRIMARY KEY (NROCONV, CORRCONV)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_PYTOPERS
    ALTER TABLE SYSCANVAS.T_PYTOPERS MODIFY (CELULAR NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PYTOPERS MODIFY (CODPYTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PYTOPERS MODIFY (CORREMPL NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PYTOPERS MODIFY (CODCARGO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PYTOPERS MODIFY (FECINI NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PYTOPERS MODIFY (FECFIN NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PYTOPERS MODIFY (FLGEMPLJEF NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PYTOPERS MODIFY (COSTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PYTOPERS MODIFY (DESQTRAB NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PYTOPERS MODIFY (OBSERVAC NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PYTOPERS MODIFY (CODPERS NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PYTOPERS MODIFY (VIGENTE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PYTOPERS ADD CONSTRAINT T_PYTOPERS_PK PRIMARY KEY (CODPYTO, CORREMPL)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_SITUACION
    ALTER TABLE SYSCANVAS.T_SITUACION MODIFY (CODFASE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_SITUACION MODIFY (CODNIVEL NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_SITUACION MODIFY (CODSITUACION NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_SITUACION MODIFY (DESSITUACION NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_SITUACION MODIFY (VIGENTE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_SITUACION ADD CONSTRAINT T_SITUACION_PK PRIMARY KEY (CODFASE, CODNIVEL, CODSITUACION)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_FASE
    ALTER TABLE SYSCANVAS.T_FASE MODIFY (CODFASE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_FASE MODIFY (DESFASE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_FASE MODIFY (VIGENCIA NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_FASE ADD CONSTRAINT T_FASE_PK PRIMARY KEY (CODFASE)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_CRITERIO_TRAMIF
    ALTER TABLE SYSCANVAS.T_CRITERIO_TRAMIF MODIFY (CODCRITERIO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CRITERIO_TRAMIF MODIFY (DENCRRITERIO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CRITERIO_TRAMIF MODIFY (VIGENCIA NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CRITERIO_TRAMIF ADD CONSTRAINT T_CRITERIO_TRAMIF_PK PRIMARY KEY (CODCRITERIO)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_RUTA
    ALTER TABLE SYSCANVAS.T_RUTA MODIFY (CODPYTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_RUTA MODIFY (CODRUTAPY NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_RUTA MODIFY (NROVERSION NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_RUTA MODIFY (CODRUTA NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_RUTA MODIFY (FECHAREGISTRO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_RUTA MODIFY (DENOMINACIONRUTA NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_RUTA MODIFY (DENOMINACIONCORTORUTA NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_RUTA MODIFY (NROKMS NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_RUTA MODIFY (ZONAGPS NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_RUTA MODIFY (PROGINICIO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_RUTA MODIFY (PROGFINAL NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_RUTA MODIFY (LATITUDINICIORUTA NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_RUTA MODIFY (LATITUDFINALRUTA NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_RUTA MODIFY (LONGITUDINICIORUTA NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_RUTA MODIFY (LONGITUDFINALRUTA NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_RUTA MODIFY (ALTITUDINICIORUTA NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_RUTA MODIFY (ALTITUDFINALRUTA NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_RUTA MODIFY (OBSERVACIONRUTA NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_RUTA MODIFY (VIGENCIA NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_RUTA MODIFY (ELABORADOPOR NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_RUTA ADD CONSTRAINT RUTA_PK PRIMARY KEY (CODPYTO, CODRUTAPY, NROVERSION)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_SUBTRAMO
    ALTER TABLE SYSCANVAS.T_SUBTRAMO MODIFY (CODPYTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_SUBTRAMO MODIFY (CODRUTAPY NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_SUBTRAMO MODIFY (CODTRAMOPY NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_SUBTRAMO MODIFY (CODSUBTRAMOPY NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_SUBTRAMO MODIFY (NROVERSION NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_SUBTRAMO MODIFY (CODSUBTRAMO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_SUBTRAMO MODIFY (FECHAREGISTRO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_SUBTRAMO MODIFY (DENOMINACIONSUBTRAMO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_SUBTRAMO MODIFY (DENOMINACIONCORTOSUBTRAMO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_SUBTRAMO MODIFY (NROKMSSUBTRAMO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_SUBTRAMO MODIFY (ZONAGPS NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_SUBTRAMO MODIFY (PROGINICIO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_SUBTRAMO MODIFY (PROGFIN NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_SUBTRAMO MODIFY (LATITUDINICIOSUBTRAMO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_SUBTRAMO MODIFY (LATITUDFINALSUBTRAMO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_SUBTRAMO MODIFY (LONGITUDINICIOSUBTRAMO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_SUBTRAMO MODIFY (LONGITUDFINALSUBTRAMO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_SUBTRAMO MODIFY (ALTITUDINICIOSUBTRAMO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_SUBTRAMO MODIFY (ALTITUDFINALSUBTRAMO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_SUBTRAMO MODIFY (OBSERVACIONSUBTRAMO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_SUBTRAMO MODIFY (VIGENCIA NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_SUBTRAMO ADD CONSTRAINT T_CODSUBTRAMOPY PRIMARY KEY (CODPYTO, CODRUTAPY, CODTRAMOPY, CODSUBTRAMOPY, NROVERSION)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_CAT_FOTO
    ALTER TABLE SYSCANVAS.T_CAT_FOTO MODIFY (CODPYTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CAT_FOTO MODIFY (CODRUTAPY NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CAT_FOTO MODIFY (NROVERSION NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CAT_FOTO MODIFY (COD_FOTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CAT_FOTO MODIFY (NOMFOTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CAT_FOTO MODIFY (FECREG NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CAT_FOTO MODIFY (RESPONSABLE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CAT_FOTO MODIFY (OBSERVACION NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CAT_FOTO ADD CONSTRAINT T_CAT_FOTO_PK PRIMARY KEY (CODPYTO, CODRUTAPY, NROVERSION, COD_FOTO)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;
    ALTER TABLE SYSCANVAS.T_CAT_FOTO MODIFY (URI NOT NULL ENABLE);

--- CONSTRAINTS TABLE T_EMPRESA
    ALTER TABLE SYSCANVAS.T_EMPRESA MODIFY (CODPERSONA NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_EMPRESA MODIFY (NRORUC NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_EMPRESA MODIFY (FLGEMPCONSORCIO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_EMPRESA MODIFY (FECINI NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_EMPRESA MODIFY (VIGENTE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_EMPRESA ADD CONSTRAINT EMPRESA_PK PRIMARY KEY (CODPERSONA)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_GPS_PYTO
    ALTER TABLE SYSCANVAS.T_GPS_PYTO MODIFY (CODPYTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_GPS_PYTO MODIFY (CODRUTAPY NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_GPS_PYTO MODIFY (CODTRAMOPY NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_GPS_PYTO MODIFY (NROVERSION NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_GPS_PYTO MODIFY (CORREL NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_GPS_PYTO MODIFY (ORDEN NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_GPS_PYTO MODIFY (LATITUD NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_GPS_PYTO MODIFY (ALTITUD NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_GPS_PYTO MODIFY (LONGITUD NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_GPS_PYTO MODIFY (SECUEN NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_GPS_PYTO ADD CONSTRAINT T_GPS_PYTO_PK PRIMARY KEY (CODPYTO, CODRUTAPY, CODTRAMOPY, NROVERSION, CORREL)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_INGEGRESO_DET
    ALTER TABLE SYSCANVAS.T_INGEGRESO_DET MODIFY (INGEGR NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_INGEGRESO_DET MODIFY (PERIODO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_INGEGRESO_DET MODIFY (CODCP NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_INGEGRESO_DET MODIFY (NROCP NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_INGEGRESO_DET MODIFY (CORRE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_INGEGRESO_DET MODIFY (CODPARTIDAI NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_INGEGRESO_DET MODIFY (DESCP NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_INGEGRESO_DET MODIFY (IDMON NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_INGEGRESO_DET MODIFY (IMPMO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_INGEGRESO_DET ADD CONSTRAINT T_INGEGRESO_DET_PK PRIMARY KEY (INGEGR, PERIODO, CODCP, NROCP, CORRE)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_CONTRATO
    ALTER TABLE SYSCANVAS.T_CONTRATO MODIFY (NROCONTRATO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CONTRATO MODIFY (CODPYTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CONTRATO MODIFY (NROCONV NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CONTRATO MODIFY (NUMCONTRATO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CONTRATO MODIFY (FECCONTRATO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CONTRATO MODIFY (FECINI NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CONTRATO MODIFY (FECFIN NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CONTRATO MODIFY (FLGFIELCUMPLIMIENTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CONTRATO ADD CONSTRAINT T_CONTRATO_PK PRIMARY KEY (NROCONTRATO)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_TRAMO
    ALTER TABLE SYSCANVAS.T_TRAMO MODIFY (CODPYTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO MODIFY (CODRUTAPY NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO MODIFY (CODTRAMOPY NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO MODIFY (NROVERSION NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO MODIFY (CODTRAMO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO MODIFY (FECHAREGISTRO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO MODIFY (DENOMINACIONTRAMO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO MODIFY (DENOMINACIONCORTOTRAMO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO MODIFY (NROKMSTRAMO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO MODIFY (ZONAGPS NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO MODIFY (PROGINICIO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO MODIFY (PROGFIN NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO MODIFY (LATITUDINICIOTRAMO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO MODIFY (LATITUDFINALTRAMO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO MODIFY (LONGITUDINICIOTRAMO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO MODIFY (LONGITUDFINALTRAMO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO MODIFY (ALTITUDINICIOTRAMO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO MODIFY (ALTITUDFINALTRAMO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO MODIFY (OBSERVACIONTRAMO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO MODIFY (VIGENCIA NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO ADD CONSTRAINT T_CODTRAMOPY PRIMARY KEY (CODPYTO, CODRUTAPY, CODTRAMOPY, NROVERSION)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_FLUJOCAJA_DET
    ALTER TABLE SYSCANVAS.T_FLUJOCAJA_DET MODIFY (ANNO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_FLUJOCAJA_DET MODIFY (CODPYTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_FLUJOCAJA_DET MODIFY (TIPO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_FLUJOCAJA_DET MODIFY (INGEGR NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_FLUJOCAJA_DET MODIFY (NIVEL NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_FLUJOCAJA_DET MODIFY (CORR NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_FLUJOCAJA_DET MODIFY (ORDEN NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_FLUJOCAJA_DET ADD CONSTRAINT T_FLUJOCAJA_DET_PK PRIMARY KEY (ANNO, CODPYTO, TIPO, INGEGR, NIVEL, CORR)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_TRAMO_VIDEOF_PREL
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEOF_PREL MODIFY (CODPYTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEOF_PREL MODIFY (CODRUTA NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEOF_PREL MODIFY (CODTRAMO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEOF_PREL MODIFY (CODVERSION NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEOF_PREL MODIFY (CORREL NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEOF_PREL MODIFY (ORDEN NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEOF_PREL MODIFY (LATITUD NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEOF_PREL MODIFY (LONGITUD NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEOF_PREL MODIFY (ALTITUD NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEOF_PREL MODIFY (PROGINI NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEOF_PREL MODIFY (PROGFIN NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEOF_PREL MODIFY (CODCRITERIO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEOF_PREL MODIFY (TIPVIDEOFOTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEOF_PREL MODIFY (SECUEN NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEOF_PREL MODIFY (DURVIDEO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEOF_PREL MODIFY (OBSERV NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEOF_PREL ADD CONSTRAINT T_TRAMO_VIDEOF_PREL_PK PRIMARY KEY (CODPYTO, CODRUTA, CODTRAMO, CODVERSION, CORREL)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_TIPOINTERVENC
    ALTER TABLE SYSCANVAS.T_TIPOINTERVENC MODIFY (TIPINTERV NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TIPOINTERVENC MODIFY (DENINTERV NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TIPOINTERVENC ADD CONSTRAINT T_TIPOINTERVENC_PK PRIMARY KEY (TIPINTERV)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_DOCUMENTO
    ALTER TABLE SYSCANVAS.T_DOCUMENTO MODIFY (CODPYTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_DOCUMENTO MODIFY (CODENTREGABLE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_DOCUMENTO MODIFY (CODPAQUETE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_DOCUMENTO MODIFY (CODDOC NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_DOCUMENTO MODIFY (DENDOC NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_DOCUMENTO MODIFY (IDDOCUM NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_DOCUMENTO MODIFY (FECREG NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_DOCUMENTO MODIFY (VIGENTE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_DOCUMENTO ADD CONSTRAINT T_DOCUMENTO_PK PRIMARY KEY (CODPYTO, CODENTREGABLE, CODPAQUETE, CODDOC)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_TIPOPAVIMENTO
    ALTER TABLE SYSCANVAS.T_TIPOPAVIMENTO MODIFY (TIPPAV NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TIPOPAVIMENTO MODIFY (DENPAV NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TIPOPAVIMENTO MODIFY (VIGENCIA NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TIPOPAVIMENTO ADD CONSTRAINT T_TIPOPAVIMENTO_PK PRIMARY KEY (TIPPAV)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_GRADO
    ALTER TABLE SYSCANVAS.T_GRADO MODIFY (CODGRADO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_GRADO MODIFY (GRADO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_GRADO ADD CONSTRAINT T_GRADO_PK PRIMARY KEY (CODGRADO)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_CAPACITACION
    ALTER TABLE SYSCANVAS.T_CAPACITACION MODIFY (CODPERS NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CAPACITACION MODIFY (CORRCAP NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CAPACITACION MODIFY (CODGRADO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CAPACITACION MODIFY (CODPROF NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CAPACITACION MODIFY (CONCENTEST NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CAPACITACION MODIFY (NOMBREINST NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CAPACITACION MODIFY (FECCAP NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CAPACITACION MODIFY (DESCAP NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CAPACITACION MODIFY (FECINI NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CAPACITACION MODIFY (FECFIN NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CAPACITACION MODIFY (NROMESES NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CAPACITACION MODIFY (FLGESCANEO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CAPACITACION MODIFY (VIGENTE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CAPACITACION ADD CONSTRAINT T_CAPACITACION_PK PRIMARY KEY (CODPERS, CORRCAP)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_PYTOHITOS
    ALTER TABLE SYSCANVAS.T_PYTOHITOS MODIFY (CODPYTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PYTOHITOS MODIFY (DESHITO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PYTOHITOS MODIFY (CUMPLITO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PYTOHITOS MODIFY (FECINICIO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PYTOHITOS MODIFY (OBSERVAC NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PYTOHITOS ADD CONSTRAINT T_PYTOHITOS_PK PRIMARY KEY (CODPYTO)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_PERSPROFESION
    ALTER TABLE SYSCANVAS.T_PERSPROFESION MODIFY (CODPERS NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PERSPROFESION MODIFY (CORRPROF NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PERSPROFESION MODIFY (CODGRADO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PERSPROFESION MODIFY (CODPROF NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PERSPROFESION MODIFY (CODCENTEST NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PERSPROFESION MODIFY (NROCIP NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PERSPROFESION MODIFY (DENCOLPROF NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PERSPROFESION MODIFY (FECCIPVIG NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PERSPROFESION MODIFY (FECTITULO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PERSPROFESION MODIFY (FECBACHILLER NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PERSPROFESION MODIFY (FECCOLEGIATURA NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PERSPROFESION MODIFY (FLGESCANEO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PERSPROFESION MODIFY (VIGENTE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PERSPROFESION ADD CONSTRAINT T_PERSPROFESION_PK PRIMARY KEY (CODPERS, CORRPROF)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_DISTRITO
    ALTER TABLE SYSCANVAS.T_DISTRITO MODIFY (CODDPTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_DISTRITO MODIFY (CODPROV NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_DISTRITO MODIFY (CODDIST NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_DISTRITO MODIFY (DESDIST NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_DISTRITO MODIFY (VIGENTE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_DISTRITO ADD CONSTRAINT T_DISTRITO_PK PRIMARY KEY (CODDPTO, CODPROV, CODDIST)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_MONEDA
    ALTER TABLE SYSCANVAS.T_MONEDA MODIFY (DENMON NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_MONEDA MODIFY (SIMBOLO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_MONEDA MODIFY (VIGENTE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_MONEDA ADD PRIMARY KEY (IDMON)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_PARTIDAING
    ALTER TABLE SYSCANVAS.T_PARTIDAING ADD CONSTRAINT T_PARTIDAING_PK PRIMARY KEY (INGEGR, CODPARTIDAI)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;
    ALTER TABLE SYSCANVAS.T_PARTIDAING MODIFY (INGEGR NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PARTIDAING MODIFY (CODPARTIDAI NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PARTIDAING MODIFY (CODPARINGR NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PARTIDAING MODIFY (DESPARTIDA NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PARTIDAING MODIFY (NIVEL NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PARTIDAING MODIFY (UNIMED NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PARTIDAING MODIFY (VIGENTE NOT NULL ENABLE);

--- CONSTRAINTS TABLE T_PRESINGRESO_DET
    ALTER TABLE SYSCANVAS.T_PRESINGRESO_DET MODIFY (CODPYTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PRESINGRESO_DET MODIFY (NROVERSION NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PRESINGRESO_DET MODIFY (INGEGR NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PRESINGRESO_DET MODIFY (CODPARTIDAI NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PRESINGRESO_DET MODIFY (IDMON NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PRESINGRESO_DET MODIFY (IMPMO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PRESINGRESO_DET MODIFY (TIPCAMBIO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PRESINGRESO_DET MODIFY (IMPMN NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PRESINGRESO_DET MODIFY (CANT NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PRESINGRESO_DET MODIFY (PERIODO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PRESINGRESO_DET MODIFY (SEMILLA1 NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PRESINGRESO_DET MODIFY (SEMILLA2 NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PRESINGRESO_DET ADD CONSTRAINT T_PRESINGRESO_DET_PK PRIMARY KEY (CODPYTO, NROVERSION, INGEGR, CODPARTIDAI)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_CAT_VIDEO
    ALTER TABLE SYSCANVAS.T_CAT_VIDEO MODIFY (CODPYTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CAT_VIDEO MODIFY (CODRUTAPY NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CAT_VIDEO MODIFY (NROVERSION NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CAT_VIDEO MODIFY (COD_VIDEO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CAT_VIDEO MODIFY (NOMVIDEO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CAT_VIDEO MODIFY (FECREG NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CAT_VIDEO MODIFY (RESPONSABLE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CAT_VIDEO MODIFY (DURACION NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CAT_VIDEO MODIFY (OBSERVACION NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CAT_VIDEO ADD CONSTRAINT T_CAT_VIDEO_PK PRIMARY KEY (CODPYTO, CODRUTAPY, NROVERSION, COD_VIDEO)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;
    ALTER TABLE SYSCANVAS.T_CAT_VIDEO MODIFY (URI NOT NULL ENABLE);

--- CONSTRAINTS TABLE T_TRAMO_GPS_PREL
    ALTER TABLE SYSCANVAS.T_TRAMO_GPS_PREL MODIFY (CODPYTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_GPS_PREL MODIFY (CODRUTA NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_GPS_PREL MODIFY (CODTRAMO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_GPS_PREL MODIFY (CODVERSION NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_GPS_PREL MODIFY (CORREL NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_GPS_PREL MODIFY (ORDEN NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_GPS_PREL MODIFY (LATITUD NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_GPS_PREL MODIFY (LONGITUD NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_GPS_PREL MODIFY (ALTITUD NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_GPS_PREL MODIFY (PROGINI NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_GPS_PREL MODIFY (PROGFIN NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_GPS_PREL MODIFY (OBSERV NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_GPS_PREL ADD CONSTRAINT T_TRAMO_GPS_PREL_PK PRIMARY KEY (CODPYTO, CODRUTA, CODTRAMO, CODVERSION, CORREL)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_CENTROESTUDIO
    ALTER TABLE SYSCANVAS.T_CENTROESTUDIO MODIFY (CODCENTEST NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CENTROESTUDIO MODIFY (DESCCENTEST NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CENTROESTUDIO MODIFY (VIGENTE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CENTROESTUDIO ADD CONSTRAINT T_CENTROESTUDIO_PK PRIMARY KEY (CODCENTEST)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_ENTREGABLE
    ALTER TABLE SYSCANVAS.T_ENTREGABLE MODIFY (CODPYTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_ENTREGABLE MODIFY (CODENTREGABLE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_ENTREGABLE MODIFY (DENENTREGABLE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_ENTREGABLE MODIFY (DENCORTA NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_ENTREGABLE MODIFY (FECREG NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_ENTREGABLE MODIFY (VIGENTE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_ENTREGABLE ADD CONSTRAINT T_ENTREGABLE_PK PRIMARY KEY (CODPYTO, CODENTREGABLE)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_OBJCONTRAT
    ALTER TABLE SYSCANVAS.T_OBJCONTRAT MODIFY (CODOBJC NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_OBJCONTRAT MODIFY (DESCOBJETO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_OBJCONTRAT MODIFY (VIGENTE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_OBJCONTRAT ADD CONSTRAINT T_OBJCONTRAT_PK PRIMARY KEY (CODOBJC)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_TIPO_CP
    ALTER TABLE SYSCANVAS.T_TIPO_CP MODIFY (DENLCP NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TIPO_CP MODIFY (DENCCP NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TIPO_CP MODIFY (VIGENTE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TIPO_CP ADD PRIMARY KEY (CODCP)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_PROFESIONES
    ALTER TABLE SYSCANVAS.T_PROFESIONES MODIFY (CODPROF NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PROFESIONES MODIFY (DESPROF NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PROFESIONES MODIFY (VIGENTE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PROFESIONES ADD CONSTRAINT T_PROFESIONES_PK PRIMARY KEY (CODPROF)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_PARTIDAEGR_1
    ALTER TABLE SYSCANVAS.T_PARTIDAEGR_1 MODIFY (IDCC NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PARTIDAEGR_1 MODIFY (CODCC NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PARTIDAEGR_1 MODIFY (DESCC NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PARTIDAEGR_1 MODIFY (FLGCC NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PARTIDAEGR_1 MODIFY (NIVEL NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PARTIDAEGR_1 MODIFY (UNIMED NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PARTIDAEGR_1 MODIFY (SEMILLA NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PARTIDAEGR_1 MODIFY (IDCCPADRE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PARTIDAEGR_1 MODIFY (VIGENTE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PARTIDAEGR_1 ADD CONSTRAINT T_PARTIDAEGR_1_PK PRIMARY KEY (IDCC)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_PROVINCIA
    ALTER TABLE SYSCANVAS.T_PROVINCIA MODIFY (CODDPTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PROVINCIA MODIFY (CODPROV NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PROVINCIA MODIFY (DESPROV NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PROVINCIA MODIFY (VIGENTE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PROVINCIA ADD CONSTRAINT T_PROVINCIA_PK PRIMARY KEY (CODDPTO, CODPROV)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_CONVOCATORIA
    ALTER TABLE SYSCANVAS.T_CONVOCATORIA MODIFY (NROCONV NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CONVOCATORIA MODIFY (CODPYTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CONVOCATORIA MODIFY (NROPROCESO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CONVOCATORIA MODIFY (DESCPROCESO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CONVOCATORIA MODIFY (CODEMPLEADO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CONVOCATORIA ADD CONSTRAINT CODPYTO__UN UNIQUE (CODPYTO)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;
    ALTER TABLE SYSCANVAS.T_CONVOCATORIA MODIFY (LUGARPRESENTACION NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CONVOCATORIA MODIFY (NOMENCLATURA NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CONVOCATORIA MODIFY (CODOBJC NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CONVOCATORIA MODIFY (RUTADOC1 NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CONVOCATORIA MODIFY (RUTADOC2 NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CONVOCATORIA MODIFY (OBSERVAC NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CONVOCATORIA ADD CONSTRAINT T_CONVOCATORIA_PK PRIMARY KEY (NROCONV)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_PERSONA
    ALTER TABLE SYSCANVAS.T_PERSONA MODIFY (CODPERSONA NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PERSONA MODIFY (TIPPERSONA NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PERSONA MODIFY (DESPERSONA NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PERSONA MODIFY (DESCORTA NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PERSONA ADD CONSTRAINT T_PERSONA_PK PRIMARY KEY (CODPERSONA)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_CONV_FECHAS
    ALTER TABLE SYSCANVAS.T_CONV_FECHAS MODIFY (NROCONV NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CONV_FECHAS MODIFY (CODHITO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CONV_FECHAS MODIFY (FECINI NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CONV_FECHAS MODIFY (FECFIN NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CONV_FECHAS ADD CONSTRAINT T_CONV_FECHAS_PK PRIMARY KEY (NROCONV, CODHITO)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_PRESINGRESO
    ALTER TABLE SYSCANVAS.T_PRESINGRESO MODIFY (CODPYTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PRESINGRESO MODIFY (NROVERSION NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PRESINGRESO MODIFY (FECREG NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PRESINGRESO MODIFY (COSDIR NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PRESINGRESO MODIFY (GASGGFIN NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PRESINGRESO MODIFY (IMPUTILIDAD NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PRESINGRESO MODIFY (IMPTOTSINIGV NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PRESINGRESO MODIFY (IMPCONIGV NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PRESINGRESO MODIFY (IMPTOTAL NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PRESINGRESO ADD CONSTRAINT T_PRESINGRESO_PK PRIMARY KEY (CODPYTO, NROVERSION)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_PROYECTO
    ALTER TABLE SYSCANVAS.T_PROYECTO MODIFY (CODPYTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PROYECTO MODIFY (CODSNIP NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PROYECTO MODIFY (FECREG NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PROYECTO MODIFY (CODFASE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PROYECTO MODIFY (CODNIVEL NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PROYECTO MODIFY (CODFUNCION NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PROYECTO MODIFY (CODTAXONOMIA NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PROYECTO MODIFY (CODSITUACION NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PROYECTO MODIFY (NUMINFOR NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PROYECTO MODIFY (NUMINFORENTRG NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PROYECTO MODIFY (ESTPYTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PROYECTO MODIFY (FECESTADO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PROYECTO MODIFY (CODCONSORCIO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PROYECTO MODIFY (NOMPYTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PROYECTO MODIFY (CODCLIENTE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PROYECTO MODIFY (EMPLJEFEPROJ NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PROYECTO MODIFY (COSTOTOTAL NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PROYECTO MODIFY (COSTODIRECTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PROYECTO MODIFY (COSTOGGEN NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PROYECTO MODIFY (COSTOIMP NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PROYECTO MODIFY (COSTOPENALID NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PROYECTO MODIFY (CODDPTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PROYECTO MODIFY (CODPROV NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PROYECTO MODIFY (CODDIST NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PROYECTO MODIFY (VIGENTE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PROYECTO ADD CONSTRAINT NUMPYTO PRIMARY KEY (CODPYTO)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_CLIENTE
    ALTER TABLE SYSCANVAS.T_CLIENTE MODIFY (CODPERSONA NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CLIENTE MODIFY (NRORUC NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CLIENTE MODIFY (VIGENTE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CLIENTE ADD CONSTRAINT T_CLIENTE_PK PRIMARY KEY (CODPERSONA)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_NIVEL
    ALTER TABLE SYSCANVAS.T_NIVEL MODIFY (CODFASE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_NIVEL MODIFY (CODNIVEL NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_NIVEL MODIFY (DESNIVEL NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_NIVEL MODIFY (VIGENTE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_NIVEL ADD CONSTRAINT T_NIVEL_PK PRIMARY KEY (CODFASE, CODNIVEL)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_ING_EGRESO
    ALTER TABLE SYSCANVAS.T_ING_EGRESO MODIFY (INGEGR NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_ING_EGRESO MODIFY (PERIODO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_ING_EGRESO MODIFY (CODCP NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_ING_EGRESO MODIFY (NROCP NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_ING_EGRESO MODIFY (CODPYTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_ING_EGRESO MODIFY (FECREG NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_ING_EGRESO ADD CONSTRAINT T_ING_EGRESO_PK PRIMARY KEY (INGEGR, PERIODO, CODCP, NROCP)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_FUNCION
    ALTER TABLE SYSCANVAS.T_FUNCION MODIFY (CODFUNCION NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_FUNCION MODIFY (DESFUNCION NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_FUNCION MODIFY (VIGENTE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_FUNCION ADD CONSTRAINT T_FUNCION_PK PRIMARY KEY (CODFUNCION)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_PAQUETE
    ALTER TABLE SYSCANVAS.T_PAQUETE MODIFY (CODPYTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PAQUETE MODIFY (CODENTREGABLE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PAQUETE MODIFY (CODPAQUETE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PAQUETE MODIFY (DENPAQUETE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PAQUETE MODIFY (DENCORTA NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PAQUETE MODIFY (FECREG NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PAQUETE MODIFY (VIGENTE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PAQUETE ADD CONSTRAINT T_PAQUETE_PK PRIMARY KEY (CODPYTO, CODENTREGABLE, CODPAQUETE)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_EXPERIENCIA
    ALTER TABLE SYSCANVAS.T_EXPERIENCIA MODIFY (CODPERS NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_EXPERIENCIA MODIFY (CORREXP NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_EXPERIENCIA MODIFY (LUGARTRABAJO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_EXPERIENCIA MODIFY (DESTRABAJO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_EXPERIENCIA MODIFY (CONTRATO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_EXPERIENCIA MODIFY (FECINI NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_EXPERIENCIA MODIFY (FECFIN NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_EXPERIENCIA MODIFY (NROMESES NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_EXPERIENCIA MODIFY (NRODIAS NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_EXPERIENCIA MODIFY (MOTIVORETIRO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_EXPERIENCIA MODIFY (CODPROF NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_EXPERIENCIA MODIFY (VIGENTE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_EXPERIENCIA ADD CONSTRAINT T_EXPERIENCIA_PK PRIMARY KEY (CODPERS, CORREXP)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_TRAMO_VIDEOF
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEOF MODIFY (CODPYTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEOF MODIFY (CODRUTAPY NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEOF MODIFY (CODTRAMOPY NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEOF MODIFY (NROVERSION NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEOF MODIFY (CORREL NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEOF MODIFY (ORDEN NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEOF MODIFY (DESCRIPCION NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEOF MODIFY (CODCRITERIO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEOF MODIFY (TIPVIDEOFOTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEOF MODIFY (CODFOTOVIDEO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEOF MODIFY (VIGENCIA NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEOF MODIFY (OBSERVACION NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEOF ADD CONSTRAINT T_TRAMO_VIDEOF_PK PRIMARY KEY (CODPYTO, CODRUTAPY, CODTRAMOPY, NROVERSION, CORREL)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_TIPO_PERSONA
    ALTER TABLE SYSCANVAS.T_TIPO_PERSONA ADD PRIMARY KEY (TIPPERSONA)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_ASEGURADORA
    ALTER TABLE SYSCANVAS.T_ASEGURADORA MODIFY (CODASEG NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_ASEGURADORA MODIFY (DENASEGURADORA NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_ASEGURADORA MODIFY (FLGASEBROK NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_ASEGURADORA MODIFY (NROCELULAR NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_ASEGURADORA MODIFY (EMAIL NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_ASEGURADORA MODIFY (OBSERVAC NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_ASEGURADORA MODIFY (VIGENCIA NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_ASEGURADORA ADD CONSTRAINT T_ASEGURADORA_PK PRIMARY KEY (CODASEG)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_TAXONOMIA
    ALTER TABLE SYSCANVAS.T_TAXONOMIA MODIFY (CODFUNCION NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TAXONOMIA MODIFY (CODTAXONOMIA NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TAXONOMIA MODIFY (DESTAX NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TAXONOMIA MODIFY (VIGENTE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TAXONOMIA ADD CONSTRAINT T_TAXONOMIA_PK PRIMARY KEY (CODFUNCION, CODTAXONOMIA)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_FLUJOCAJA
    ALTER TABLE SYSCANVAS.T_FLUJOCAJA MODIFY (CODPYTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_FLUJOCAJA MODIFY (TIPO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_FLUJOCAJA MODIFY (INGEGR NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_FLUJOCAJA MODIFY (NIVEL NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_FLUJOCAJA MODIFY (CORR NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_FLUJOCAJA MODIFY (DESCONCEPTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_FLUJOCAJA MODIFY (ORDEN NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_FLUJOCAJA ADD CONSTRAINT T_FLUJOCAJA_PK PRIMARY KEY (CODPYTO, TIPO, INGEGR, NIVEL, CORR)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_DEPARTAMENTO
    ALTER TABLE SYSCANVAS.T_DEPARTAMENTO MODIFY (CODDPTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_DEPARTAMENTO MODIFY (DESDPTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_DEPARTAMENTO MODIFY (VIGENTE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_DEPARTAMENTO ADD CONSTRAINT T_DEPARTAMENTO_PK PRIMARY KEY (CODDPTO)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_HITOSCONV
    ALTER TABLE SYSCANVAS.T_HITOSCONV MODIFY (CODHITO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_HITOSCONV MODIFY (DESCHITO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_HITOSCONV MODIFY (VIGENTE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_HITOSCONV ADD CONSTRAINT T_HITOSCONV_PK PRIMARY KEY (CODHITO)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_PYTOCLIENTESP
    ALTER TABLE SYSCANVAS.T_PYTOCLIENTESP MODIFY (CODPYTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PYTOCLIENTESP MODIFY (CORREMPL NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PYTOCLIENTESP MODIFY (CODCLIENTE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PYTOCLIENTESP MODIFY (DESPERSONA NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PYTOCLIENTESP MODIFY (CODCARGO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PYTOCLIENTESP MODIFY (FECINI NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PYTOCLIENTESP MODIFY (FECFIN NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PYTOCLIENTESP MODIFY (FLGEMPLJEF NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PYTOCLIENTESP MODIFY (COSTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PYTOCLIENTESP MODIFY (DESQTRAB NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PYTOCLIENTESP MODIFY (OBSERVAC NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PYTOCLIENTESP MODIFY (VIGENTE NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_PYTOCLIENTESP ADD CONSTRAINT T_PYTOCLIENTESP_PK PRIMARY KEY (CODPYTO, CORREMPL)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_TRAMO_VIDEODET
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEODET MODIFY (CODPYTO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEODET MODIFY (CODRUTAPY NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEODET MODIFY (CODTRAMOPY NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEODET MODIFY (NROVERSION NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEODET MODIFY (CORREL NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEODET MODIFY (SECUEN NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEODET MODIFY (ORDEN NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEODET MODIFY (DESCRIPCION NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEODET MODIFY (TIPPAV NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEODET MODIFY (TIPINTERV NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEODET MODIFY (OBSERVAC NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEODET MODIFY (FLGVIGENCIA NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEODET ADD CONSTRAINT T_TRAMO_VIDEODET_PK PRIMARY KEY (CODPYTO, CODRUTAPY, CODTRAMOPY, NROVERSION, CORREL, SECUEN)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

--- CONSTRAINTS TABLE T_CARGO
    ALTER TABLE SYSCANVAS.T_CARGO MODIFY (CODCARGO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CARGO MODIFY (DESCARGO NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CARGO MODIFY (FLGMIEMPRESA NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CARGO MODIFY (VIGENCIA NOT NULL ENABLE);
    ALTER TABLE SYSCANVAS.T_CARGO ADD CONSTRAINT T_CARGO_PK PRIMARY KEY (CODCARGO)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;
