--- FOREIGN KEY TABLE T_CAPACITACION
    ALTER TABLE SYSCANVAS.T_CAPACITACION ADD CONSTRAINT CENTROESTUDIO_CAPACITACION_FK FOREIGN KEY (CONCENTEST)
        REFERENCES SYSCANVAS.T_CENTROESTUDIO (CODCENTEST) ENABLE;
    ALTER TABLE SYSCANVAS.T_CAPACITACION ADD CONSTRAINT GRADO_1_CAPACITACION_FK FOREIGN KEY (CODGRADO)
        REFERENCES SYSCANVAS.T_GRADO (CODGRADO) ENABLE;
    ALTER TABLE SYSCANVAS.T_CAPACITACION ADD CONSTRAINT PROFESIONES_CAPACITACION_FK FOREIGN KEY (CODPROF)
        REFERENCES SYSCANVAS.T_PROFESIONES (CODPROF) ENABLE;
    ALTER TABLE SYSCANVAS.T_CAPACITACION ADD CONSTRAINT EMPLEADO_CAPACITACION_FK FOREIGN KEY (CODPERS)
        REFERENCES SYSCANVAS.T_EMPLEADO (CODPERS) ENABLE;

--- FOREIGN KEY TABLE T_CAT_FOTO
    ALTER TABLE SYSCANVAS.T_CAT_FOTO ADD CONSTRAINT T_RUTA_CAT_FOTO_FK FOREIGN KEY (CODPYTO, CODRUTAPY, NROVERSION)
        REFERENCES SYSCANVAS.T_RUTA (CODPYTO, CODRUTAPY, NROVERSION) ENABLE;

--- FOREIGN KEY TABLE T_CAT_VIDEO
    ALTER TABLE SYSCANVAS.T_CAT_VIDEO ADD CONSTRAINT T_RUTA_CAT_VIDEO_FK FOREIGN KEY (CODPYTO, CODRUTAPY, NROVERSION)
        REFERENCES SYSCANVAS.T_RUTA (CODPYTO, CODRUTAPY, NROVERSION) ENABLE;

--- FOREIGN KEY TABLE T_CLIENTE
    ALTER TABLE SYSCANVAS.T_CLIENTE ADD CONSTRAINT T_PERSONA_CLIENTE_FK FOREIGN KEY (CODPERSONA)
        REFERENCES SYSCANVAS.T_PERSONA (CODPERSONA) ENABLE;
    ALTER TABLE SYSCANVAS.T_CLIENTE ADD CONSTRAINT T_DISTRITO_CLIENTE1_FK FOREIGN KEY (CODDPTO, CODPROV, CODDIST)
        REFERENCES SYSCANVAS.T_DISTRITO (CODDPTO, CODPROV, CODDIST) ENABLE;

--- FOREIGN KEY TABLE T_CONTRATO
    ALTER TABLE SYSCANVAS.T_CONTRATO ADD CONSTRAINT ASEGURADORA_CONTRATO_FK FOREIGN KEY (CODASEGFIELCUM)
        REFERENCES SYSCANVAS.T_ASEGURADORA (CODASEG) ENABLE;
    ALTER TABLE SYSCANVAS.T_CONTRATO ADD CONSTRAINT ASEGURADORA_CONTRATO_FK1 FOREIGN KEY (CODBROKERFIELCUM)
        REFERENCES SYSCANVAS.T_ASEGURADORA (CODASEG) ENABLE;
    ALTER TABLE SYSCANVAS.T_CONTRATO ADD CONSTRAINT ASEGURADORA_CONTRATO_FK2 FOREIGN KEY (CODASEGADEL)
        REFERENCES SYSCANVAS.T_ASEGURADORA (CODASEG) ENABLE;
    ALTER TABLE SYSCANVAS.T_CONTRATO ADD CONSTRAINT ASEGURADORA_CONTRATO_FK3 FOREIGN KEY (CODBROKERADEL)
        REFERENCES SYSCANVAS.T_ASEGURADORA (CODASEG) ENABLE;
    ALTER TABLE SYSCANVAS.T_CONTRATO ADD CONSTRAINT PROYECTO_CONTRATO_FK FOREIGN KEY (CODPYTO)
        REFERENCES SYSCANVAS.T_PROYECTO (CODPYTO) ENABLE;
    ALTER TABLE SYSCANVAS.T_CONTRATO ADD CONSTRAINT CONVOCATORIA_CONTRATO_FK FOREIGN KEY (NROCONV)
        REFERENCES SYSCANVAS.T_CONVOCATORIA (NROCONV) ENABLE;

--- FOREIGN KEY TABLE T_CONV_FECHAS
    ALTER TABLE SYSCANVAS.T_CONV_FECHAS ADD CONSTRAINT HITTOSCONV_CONV_FECHAS_FK FOREIGN KEY (CODHITO)
        REFERENCES SYSCANVAS.T_HITOSCONV (CODHITO) ENABLE;
    ALTER TABLE SYSCANVAS.T_CONV_FECHAS ADD CONSTRAINT CONVOCATORIA_CONV_FECHAS_FK FOREIGN KEY (NROCONV)
        REFERENCES SYSCANVAS.T_CONVOCATORIA (NROCONV) ENABLE;

--- FOREIGN KEY TABLE T_CONVOCATORIA
    ALTER TABLE SYSCANVAS.T_CONVOCATORIA ADD CONSTRAINT OBJCONTRAT_CONVOCATORIA_FK FOREIGN KEY (CODOBJC)
        REFERENCES SYSCANVAS.T_OBJCONTRAT (CODOBJC) ENABLE;
    ALTER TABLE SYSCANVAS.T_CONVOCATORIA ADD CONSTRAINT EMPLEADO_CONVOCATORIA_FK FOREIGN KEY (CODEMPLEADO)
        REFERENCES SYSCANVAS.T_EMPLEADO (CODPERS) ENABLE;
    ALTER TABLE SYSCANVAS.T_CONVOCATORIA ADD CONSTRAINT CLIENTE_CONVOCATORIA_FK FOREIGN KEY (CODCLIENTE)
        REFERENCES SYSCANVAS.T_CLIENTE (CODPERSONA) ENABLE;
    ALTER TABLE SYSCANVAS.T_CONVOCATORIA ADD CONSTRAINT PROYECTO_CONVOCATORIA_FK FOREIGN KEY (CODPYTO)
        REFERENCES SYSCANVAS.T_PROYECTO (CODPYTO) ENABLE;

--- FOREIGN KEY TABLE T_DISTRITO
    ALTER TABLE SYSCANVAS.T_DISTRITO ADD CONSTRAINT T_PROVINCIA_DISTRITO_FK FOREIGN KEY (CODDPTO, CODPROV)
        REFERENCES SYSCANVAS.T_PROVINCIA (CODDPTO, CODPROV) ENABLE;

--- FOREIGN KEY TABLE T_DOCUMENTO
    ALTER TABLE SYSCANVAS.T_DOCUMENTO ADD CONSTRAINT T_TIPO_DOC_DOCUMENTO_FK FOREIGN KEY (TIPDOC)
        REFERENCES SYSCANVAS.T_TIPO_DOC (TIPDOC) ENABLE;
    ALTER TABLE SYSCANVAS.T_DOCUMENTO ADD CONSTRAINT T_PAQUETE_DOCUMENTO_FK FOREIGN KEY (CODPYTO, CODENTREGABLE, CODPAQUETE)
        REFERENCES SYSCANVAS.T_PAQUETE (CODPYTO, CODENTREGABLE, CODPAQUETE) ENABLE;

--- FOREIGN KEY TABLE T_EMPLEADO
    ALTER TABLE SYSCANVAS.T_EMPLEADO ADD CONSTRAINT T_CARGO_EMPLEADO_FK FOREIGN KEY (CODCARGO)
        REFERENCES SYSCANVAS.T_CARGO (CODCARGO) ENABLE;
    ALTER TABLE SYSCANVAS.T_EMPLEADO ADD CONSTRAINT T_PERSONA_EMPLEADO_FK FOREIGN KEY (CODPERS)
        REFERENCES SYSCANVAS.T_PERSONA (CODPERSONA) ENABLE;

--- FOREIGN KEY TABLE T_EMPRESA
    ALTER TABLE SYSCANVAS.T_EMPRESA ADD CONSTRAINT T_PERSONA_EMPRESA_FK FOREIGN KEY (CODPERSONA)
        REFERENCES SYSCANVAS.T_PERSONA (CODPERSONA) ENABLE;

--- FOREIGN KEY TABLE T_ENTREGABLE
    ALTER TABLE SYSCANVAS.T_ENTREGABLE ADD CONSTRAINT T_PROYECTO_ENTREGABLE_FK FOREIGN KEY (CODPYTO)
        REFERENCES SYSCANVAS.T_PROYECTO (CODPYTO) ENABLE;

--- FOREIGN KEY TABLE T_ESTADO
    ALTER TABLE SYSCANVAS.T_ESTADO ADD CONSTRAINT T_NIVEL_ESTADO_FK FOREIGN KEY (CODFASE, CODNIVEL)
        REFERENCES SYSCANVAS.T_NIVEL (CODFASE, CODNIVEL) ENABLE;

--- FOREIGN KEY TABLE T_EXPERIENCIA
    ALTER TABLE SYSCANVAS.T_EXPERIENCIA ADD CONSTRAINT PROFESIONES_EXPERIENCIA_FK FOREIGN KEY (CODPROF)
        REFERENCES SYSCANVAS.T_PROFESIONES (CODPROF) ENABLE;
    ALTER TABLE SYSCANVAS.T_EXPERIENCIA ADD CONSTRAINT T_EMPLEADO_EXPERIENCIA_FK FOREIGN KEY (CODPERS)
        REFERENCES SYSCANVAS.T_EMPLEADO (CODPERS) ENABLE;

--- FOREIGN KEY TABLE T_FLUJOCAJA
    ALTER TABLE SYSCANVAS.T_FLUJOCAJA ADD CONSTRAINT PROYECTO_FLUJOCAJA_FK FOREIGN KEY (CODPYTO)
        REFERENCES SYSCANVAS.T_PROYECTO (CODPYTO) ENABLE;

--- FOREIGN KEY TABLE T_FLUJOCAJA_DET
    ALTER TABLE SYSCANVAS.T_FLUJOCAJA_DET ADD CONSTRAINT FLUJOCAJA_FLUJOCAJA_DET_FK FOREIGN KEY (CODPYTO, TIPO, INGEGR, NIVEL, CORR)
        REFERENCES SYSCANVAS.T_FLUJOCAJA (CODPYTO, TIPO, INGEGR, NIVEL, CORR) ENABLE;

--- FOREIGN KEY TABLE T_GPS_PYTO
    ALTER TABLE SYSCANVAS.T_GPS_PYTO ADD CONSTRAINT T_CRITERIO_TRAMIF_GPS_PYTO_FK FOREIGN KEY (CODCRITERIO)
        REFERENCES SYSCANVAS.T_CRITERIO_TRAMIF (CODCRITERIO) ENABLE;
    ALTER TABLE SYSCANVAS.T_GPS_PYTO ADD CONSTRAINT T_TRAMO_GPS_PYTO_FK FOREIGN KEY (CODPYTO, CODRUTAPY, CODTRAMOPY, NROVERSION)
        REFERENCES SYSCANVAS.T_TRAMO (CODPYTO, CODRUTAPY, CODTRAMOPY, NROVERSION) ENABLE;

--- FOREIGN KEY TABLE T_ING_EGRESO
    ALTER TABLE SYSCANVAS.T_ING_EGRESO ADD CONSTRAINT PROYECTO_EGRESOS_FK FOREIGN KEY (CODPYTO)
        REFERENCES SYSCANVAS.T_PROYECTO (CODPYTO) ENABLE;

--- FOREIGN KEY TABLE T_INGEGRESO_DET
    ALTER TABLE SYSCANVAS.T_INGEGRESO_DET ADD CONSTRAINT PARTIDAEGR_EGRESOS_DET_FK FOREIGN KEY (INGEGR, CODPARTIDAI)
        REFERENCES SYSCANVAS.T_PARTIDAING (INGEGR, CODPARTIDAI) ENABLE;
    ALTER TABLE SYSCANVAS.T_INGEGRESO_DET ADD CONSTRAINT PRESEGRESO_PRESEGRESO_DET_FK FOREIGN KEY (INGEGR, PERIODO, CODCP, NROCP)
        REFERENCES SYSCANVAS.T_ING_EGRESO (INGEGR, PERIODO, CODCP, NROCP) ENABLE;

--- FOREIGN KEY TABLE T_NIVEL
    ALTER TABLE SYSCANVAS.T_NIVEL ADD CONSTRAINT T_FASE_NIVEL_FK FOREIGN KEY (CODFASE)
        REFERENCES SYSCANVAS.T_FASE (CODFASE) ENABLE;

--- FOREIGN KEY TABLE T_PAQUETE
    ALTER TABLE SYSCANVAS.T_PAQUETE ADD CONSTRAINT T_ENTREGABLE_PAQUETE_FK FOREIGN KEY (CODPYTO, CODENTREGABLE)
        REFERENCES SYSCANVAS.T_ENTREGABLE (CODPYTO, CODENTREGABLE) ENABLE;

--- FOREIGN KEY TABLE T_PARTIDAING
    ALTER TABLE SYSCANVAS.T_PARTIDAING ADD CONSTRAINT CENTROCOSTO_CENTROCOSTO_FK FOREIGN KEY (PARENT_INGEGR, IDCCPADRE)
        REFERENCES SYSCANVAS.T_PARTIDAING (INGEGR, CODPARTIDAI) ENABLE;

--- FOREIGN KEY TABLE T_PERSONA
    ALTER TABLE SYSCANVAS.T_PERSONA ADD FOREIGN KEY (TIPPERSONA)
        REFERENCES SYSCANVAS.T_TIPO_PERSONA (TIPPERSONA) ENABLE;

--- FOREIGN KEY TABLE T_PERSPROFESION
    ALTER TABLE SYSCANVAS.T_PERSPROFESION ADD CONSTRAINT CENTROESTUDIO_PERSPROFESION_FK FOREIGN KEY (CODCENTEST)
        REFERENCES SYSCANVAS.T_CENTROESTUDIO (CODCENTEST) ENABLE;
    ALTER TABLE SYSCANVAS.T_PERSPROFESION ADD CONSTRAINT GRADO_PERSPROFESION_FK FOREIGN KEY (CODGRADO)
        REFERENCES SYSCANVAS.T_GRADO (CODGRADO) ENABLE;
    ALTER TABLE SYSCANVAS.T_PERSPROFESION ADD CONSTRAINT PROFESIONES_EMPLPROFESION_FK FOREIGN KEY (CODPROF)
        REFERENCES SYSCANVAS.T_PROFESIONES (CODPROF) ENABLE;
    ALTER TABLE SYSCANVAS.T_PERSPROFESION ADD CONSTRAINT EMPLEADO_PERSPROFESION_FK FOREIGN KEY (CODPERS)
        REFERENCES SYSCANVAS.T_EMPLEADO (CODPERS) ENABLE;

--- FOREIGN KEY TABLE T_PRESINGRESO
    ALTER TABLE SYSCANVAS.T_PRESINGRESO ADD CONSTRAINT PROYECTO_PRESEGRESO_FK FOREIGN KEY (CODPYTO)
        REFERENCES SYSCANVAS.T_PROYECTO (CODPYTO) ENABLE;

--- FOREIGN KEY TABLE T_PRESINGRESO_DET
    ALTER TABLE SYSCANVAS.T_PRESINGRESO_DET ADD CONSTRAINT CENTROCOSTO_PRESEGRESO_DET_FK FOREIGN KEY (INGEGR, CODPARTIDAI)
        REFERENCES SYSCANVAS.T_PARTIDAING (INGEGR, CODPARTIDAI) ENABLE;
    ALTER TABLE SYSCANVAS.T_PRESINGRESO_DET ADD CONSTRAINT PRESEGRESO_PRESEGRESO_DET02_FK FOREIGN KEY (CODPYTO, NROVERSION)
        REFERENCES SYSCANVAS.T_PRESINGRESO (CODPYTO, NROVERSION) ENABLE;

--- FOREIGN KEY TABLE T_PROVINCIA
    ALTER TABLE SYSCANVAS.T_PROVINCIA ADD CONSTRAINT T_DEPARTAMENTO_PROVINCIA_FK FOREIGN KEY (CODDPTO)
        REFERENCES SYSCANVAS.T_DEPARTAMENTO (CODDPTO) ENABLE;

--- FOREIGN KEY TABLE T_PROYECTO
    ALTER TABLE SYSCANVAS.T_PROYECTO ADD CONSTRAINT T_EMPRESA_PROYECTO_FK FOREIGN KEY (CODCONSORCIO)
        REFERENCES SYSCANVAS.T_EMPRESA (CODPERSONA) ENABLE;
    ALTER TABLE SYSCANVAS.T_PROYECTO ADD CONSTRAINT T_EMPLEADO_PROYECTO_FK FOREIGN KEY (EMPLJEFEPROJ)
        REFERENCES SYSCANVAS.T_EMPLEADO (CODPERS) ENABLE;
    ALTER TABLE SYSCANVAS.T_PROYECTO ADD CONSTRAINT T_DISTRITO_PROYECTO_FK FOREIGN KEY (CODDPTO, CODPROV, CODDIST)
        REFERENCES SYSCANVAS.T_DISTRITO (CODDPTO, CODPROV, CODDIST) ENABLE;
    ALTER TABLE SYSCANVAS.T_PROYECTO ADD CONSTRAINT T_CLIENTE_PROYECTO_FK FOREIGN KEY (CODCLIENTE)
        REFERENCES SYSCANVAS.T_CLIENTE (CODPERSONA) ENABLE;
    ALTER TABLE SYSCANVAS.T_PROYECTO ADD CONSTRAINT T_TAXONOMIA_PROYECTO_FK FOREIGN KEY (CODFUNCION, CODTAXONOMIA)
        REFERENCES SYSCANVAS.T_TAXONOMIA (CODFUNCION, CODTAXONOMIA) ENABLE;
    ALTER TABLE SYSCANVAS.T_PROYECTO ADD CONSTRAINT T_NIVEL_PROYECTO_FK FOREIGN KEY (CODFASE, CODNIVEL)
        REFERENCES SYSCANVAS.T_NIVEL (CODFASE, CODNIVEL) ENABLE;
    ALTER TABLE SYSCANVAS.T_PROYECTO ADD CONSTRAINT SITUACION_PROYECTO_FK FOREIGN KEY (CODFASE, CODNIVEL, CODSITUACION)
        REFERENCES SYSCANVAS.T_SITUACION (CODFASE, CODNIVEL, CODSITUACION) ENABLE;
    ALTER TABLE SYSCANVAS.T_PROYECTO ADD CONSTRAINT T_ESTADO_PROYECTO_FK FOREIGN KEY (ESTPYTO, CODFASE, CODNIVEL)
        REFERENCES SYSCANVAS.T_ESTADO (ESTPYTO, CODFASE, CODNIVEL) ENABLE;

--- FOREIGN KEY TABLE T_PYTOCLIENTESP 
    ALTER TABLE SYSCANVAS.T_PYTOCLIENTESP ADD CONSTRAINT T_CARGO_PYTOCLIENTESP_FK FOREIGN KEY (CODCARGO)
        REFERENCES SYSCANVAS.T_CARGO (CODCARGO) ENABLE;
    ALTER TABLE SYSCANVAS.T_PYTOCLIENTESP ADD CONSTRAINT T_CLIENTE_PYTOCLIENTESP_FK FOREIGN KEY (CODCLIENTE)
        REFERENCES SYSCANVAS.T_CLIENTE (CODPERSONA) ENABLE;
    ALTER TABLE SYSCANVAS.T_PYTOCLIENTESP ADD CONSTRAINT T_PROYECTO_PYTOCLIENTESP_FK FOREIGN KEY (CODPYTO)
        REFERENCES SYSCANVAS.T_PROYECTO (CODPYTO) ENABLE;

--- FOREIGN KEY TABLE T_PYTOHITOS
    ALTER TABLE SYSCANVAS.T_PYTOHITOS ADD CONSTRAINT T_PROYECTO_PYTOHITOS_FK FOREIGN KEY (CODPYTO)
        REFERENCES SYSCANVAS.T_PROYECTO (CODPYTO) ENABLE;

--- FOREIGN KEY TABLE T_PYTOPERS
    ALTER TABLE SYSCANVAS.T_PYTOPERS ADD CONSTRAINT T_CARGO_PYTOPERS_FK FOREIGN KEY (CODCARGO)
        REFERENCES SYSCANVAS.T_CARGO (CODCARGO) ENABLE;
    ALTER TABLE SYSCANVAS.T_PYTOPERS ADD CONSTRAINT T_EMPLEADO_PYTOPERS_FK FOREIGN KEY (CODPERS)
        REFERENCES SYSCANVAS.T_EMPLEADO (CODPERS) ENABLE;
    ALTER TABLE SYSCANVAS.T_PYTOPERS ADD CONSTRAINT T_PROYECTO_PYTOPERS_FK FOREIGN KEY (CODPYTO)
        REFERENCES SYSCANVAS.T_PROYECTO (CODPYTO) ENABLE;

--- FOREIGN KEY TABLE T_RESULCONV
    ALTER TABLE SYSCANVAS.T_RESULCONV ADD CONSTRAINT CONVOCATORIA_RESULCONV_FK FOREIGN KEY (NROCONV)
        REFERENCES SYSCANVAS.T_CONVOCATORIA (NROCONV) ENABLE;

--- FOREIGN KEY TABLE T_RUTA
    ALTER TABLE SYSCANVAS.T_RUTA ADD CONSTRAINT T_EMPLEADO_RUTA_FK FOREIGN KEY (ELABORADOPOR)
        REFERENCES SYSCANVAS.T_EMPLEADO (CODPERS) ENABLE;
    ALTER TABLE SYSCANVAS.T_RUTA ADD CONSTRAINT T_PROYECTO_RUTA_FK FOREIGN KEY (CODPYTO)
        REFERENCES SYSCANVAS.T_PROYECTO (CODPYTO) ENABLE;

--- FOREIGN KEY TABLE T_SITUACION
    ALTER TABLE SYSCANVAS.T_SITUACION ADD CONSTRAINT T_NIVEL_SITUACION_FK FOREIGN KEY (CODFASE, CODNIVEL)
        REFERENCES SYSCANVAS.T_NIVEL (CODFASE, CODNIVEL) ENABLE;

--- FOREIGN KEY TABLE T_SUBTRAMO
    ALTER TABLE SYSCANVAS.T_SUBTRAMO ADD CONSTRAINT T_TRAMO_SUBTRAMO_FK FOREIGN KEY (CODPYTO, CODRUTAPY, CODTRAMOPY, NROVERSION)
        REFERENCES SYSCANVAS.T_TRAMO (CODPYTO, CODRUTAPY, CODTRAMOPY, NROVERSION) ENABLE;

--- FOREIGN KEY TABLE T_TAXONOMIA
    ALTER TABLE SYSCANVAS.T_TAXONOMIA ADD CONSTRAINT T_FUNCION_TAXONOMIA_FK FOREIGN KEY (CODFUNCION)
        REFERENCES SYSCANVAS.T_FUNCION (CODFUNCION) ENABLE;

--- FOREIGN KEY TABLE T_TRAMO
    ALTER TABLE SYSCANVAS.T_TRAMO ADD CONSTRAINT T_RUTA_TRAMO_FK FOREIGN KEY (CODPYTO, CODRUTAPY, NROVERSION)
        REFERENCES SYSCANVAS.T_RUTA (CODPYTO, CODRUTAPY, NROVERSION) ENABLE;

--- FOREIGN KEY TABLE T_TRAMO_VIDEODET
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEODET ADD CONSTRAINT T_TIPOINTERVENC_TRAMO_VIDEODET_FK FOREIGN KEY (TIPINTERV)
        REFERENCES SYSCANVAS.T_TIPOINTERVENC (TIPINTERV) ENABLE;
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEODET ADD CONSTRAINT T_TIPOPAVIMENTO_TRAMO_VIDEODET_FK FOREIGN KEY (TIPPAV)
        REFERENCES SYSCANVAS.T_TIPOPAVIMENTO (TIPPAV) ENABLE;

--- FOREIGN KEY TABLE T_TRAMO_VIDEOF
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEOF ADD CONSTRAINT T_CRITERIO_TRAMIF_TRAMO_VIDEO_FK FOREIGN KEY (CODCRITERIO)
        REFERENCES SYSCANVAS.T_CRITERIO_TRAMIF (CODCRITERIO) ENABLE;

--- FOREIGN KEY TABLE T_TRAMO_VIDEOF_PREL
    ALTER TABLE SYSCANVAS.T_TRAMO_VIDEOF_PREL ADD CONSTRAINT T_CRITERIO_TRAMIF_TRAMO_VIDEOF_PREL_FK FOREIGN KEY (CODCRITERIO)
        REFERENCES SYSCANVAS.T_CRITERIO_TRAMIF (CODCRITERIO) ENABLE;
