---- ÍNDICE T_OBJCONTRAT_PK
CREATE UNIQUE INDEX SYSCANVAS.T_OBJCONTRAT_PK ON SYSCANVAS.T_OBJCONTRAT (CODOBJC) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

---- ÍNDICE T_CLIENTE_PK
CREATE UNIQUE INDEX SYSCANVAS.T_CLIENTE_PK ON SYSCANVAS.T_CLIENTE (CODPERSONA) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

---- ÍNDICE T_EMPLEADO_PK
CREATE UNIQUE INDEX SYSCANVAS.T_EMPLEADO_PK ON SYSCANVAS.T_EMPLEADO (CODPERS) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

---- ÍNDICE T_EXPERIENCIA_PK
CREATE UNIQUE INDEX SYSCANVAS.T_EXPERIENCIA_PK ON SYSCANVAS.T_EXPERIENCIA (CODPERS, CORREXP) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

---- ÍNDICE T_CONV_FECHAS_PK
CREATE UNIQUE INDEX SYSCANVAS.T_CONV_FECHAS_PK ON SYSCANVAS.T_CONV_FECHAS (NROCONV, CODHITO) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

COMMIT;

---- ÍNDICE T_CENTROESTUDIO_PK
CREATE UNIQUE INDEX SYSCANVAS.T_CENTROESTUDIO_PK ON SYSCANVAS.T_CENTROESTUDIO (CODCENTEST) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ;

---- ÍNDICE T_FLUJOCAJA_DET_PK
CREATE UNIQUE INDEX SYSCANVAS.T_FLUJOCAJA_DET_PK ON SYSCANVAS.T_FLUJOCAJA_DET (ANNO, CODPYTO, TIPO, INGEGR, NIVEL, CORR) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

---- ÍNDICE T_ESTADO_PK
CREATE UNIQUE INDEX SYSCANVAS.T_ESTADO_PK ON SYSCANVAS.T_ESTADO (ESTPYTO, CODFASE, CODNIVEL) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

---- ÍNDICE T_CONTRATO_PK
CREATE UNIQUE INDEX SYSCANVAS.T_CONTRATO_PK ON SYSCANVAS.T_CONTRATO (NROCONTRATO) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ;

---- ÍNDICE T_TRAMO_VIDEOF_PREL_PK
CREATE UNIQUE INDEX SYSCANVAS.T_TRAMO_VIDEOF_PREL_PK ON SYSCANVAS.T_TRAMO_VIDEOF_PREL (CODPYTO, CODRUTA, CODTRAMO, CODVERSION, CORREL) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ;

COMMIT;

---- ÍNDICE T_FLUJOCAJA_PK
CREATE UNIQUE INDEX SYSCANVAS.T_FLUJOCAJA_PK ON SYSCANVAS.T_FLUJOCAJA (CODPYTO, TIPO, INGEGR, NIVEL, CORR) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

---- ÍNDICE T_TAXONOMIA_PK
CREATE UNIQUE INDEX SYSCANVAS.T_TAXONOMIA_PK ON SYSCANVAS.T_TAXONOMIA (CODFUNCION, CODTAXONOMIA) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

---- ÍNDICE NUMPYTO
CREATE UNIQUE INDEX SYSCANVAS.NUMPYTO ON SYSCANVAS.T_PROYECTO (CODPYTO) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

---- ÍNDICE T_INGEGRESO_DET_PK
CREATE UNIQUE INDEX SYSCANVAS.T_INGEGRESO_DET_PK ON SYSCANVAS.T_INGEGRESO_DET (INGEGR, PERIODO, CODCP, NROCP, CORRE) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

---- ÍNDICE T_ING_EGRESO_PK
CREATE UNIQUE INDEX SYSCANVAS.T_ING_EGRESO_PK ON SYSCANVAS.T_ING_EGRESO (INGEGR, PERIODO, CODCP, NROCP) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

COMMIT;

---- ÍNDICE T_TIPOINTERVENC_PK
CREATE UNIQUE INDEX SYSCANVAS.T_TIPOINTERVENC_PK ON SYSCANVAS.T_TIPOINTERVENC (TIPINTERV) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

---- ÍNDICE T_GPS_PYTO_PK
CREATE UNIQUE INDEX SYSCANVAS.T_GPS_PYTO_PK ON SYSCANVAS.T_GPS_PYTO (CODPYTO, CODRUTAPY, CODTRAMOPY, NROVERSION, CORREL) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ;

---- ÍNDICE T_CODTRAMOPY
CREATE UNIQUE INDEX SYSCANVAS.T_CODTRAMOPY ON SYSCANVAS.T_TRAMO (CODPYTO, CODRUTAPY, CODTRAMOPY, NROVERSION) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

---- ÍNDICE T_CODSUBTRAMOPY
CREATE UNIQUE INDEX SYSCANVAS.T_CODSUBTRAMOPY ON SYSCANVAS.T_SUBTRAMO (CODPYTO, CODRUTAPY, CODTRAMOPY, CODSUBTRAMOPY, NROVERSION) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

---- ÍNDICE T_RUTA_PK
CREATE UNIQUE INDEX SYSCANVAS.T_RUTA_PK ON SYSCANVAS.T_RUTA (CODPYTO, CODRUTAPY, NROVERSION) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

COMMIT;

---- ÍNDICE T_PRESINGRESO_DET_PK
CREATE UNIQUE INDEX SYSCANVAS.T_PRESINGRESO_DET_PK ON SYSCANVAS.T_PRESINGRESO_DET (CODPYTO, NROVERSION, INGEGR, CODPARTIDAI) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

---- ÍNDICE T_PYTOCLIENTESP_PK
CREATE UNIQUE INDEX SYSCANVAS.T_PYTOCLIENTESP_PK ON SYSCANVAS.T_PYTOCLIENTESP (CODPYTO, CORREMPL) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

---- ÍNDICE T_RESULCONV_PK
CREATE UNIQUE INDEX SYSCANVAS.T_RESULCONV_PK ON SYSCANVAS.T_RESULCONV (NROCONV, CORRCONV) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

---- ÍNDICE T_NIVEL_PK
CREATE UNIQUE INDEX SYSCANVAS.T_NIVEL_PK ON SYSCANVAS.T_NIVEL (CODFASE, CODNIVEL) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

--- ÍNDICE T_DISTRITO_PK
CREATE UNIQUE INDEX SYSCANVAS.T_DISTRITO_PK ON SYSCANVAS.T_DISTRITO (CODDPTO, CODPROV, CODDIST) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

COMMIT;

---- ÍNDICE T_DOCUMENTO_PK
CREATE UNIQUE INDEX SYSCANVAS.T_DOCUMENTO_PK ON SYSCANVAS.T_DOCUMENTO (CODPYTO, CODENTREGABLE, CODPAQUETE, CODDOC) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

---- ÍNDICE T_TRAMO_VIDEODET_PK
CREATE UNIQUE INDEX SYSCANVAS.T_TRAMO_VIDEODET_PK ON SYSCANVAS.T_TRAMO_VIDEODET (CODPYTO, CODRUTAPY, CODTRAMOPY, NROVERSION, CORREL, SECUEN) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

---- ÍNDICE T_GRADO_PK
CREATE UNIQUE INDEX SYSCANVAS.T_GRADO_PK ON SYSCANVAS.T_GRADO (CODGRADO) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ;

---- ÍNDICE T_PAQUETE_PK
CREATE UNIQUE INDEX SYSCANVAS.T_PAQUETE_PK ON SYSCANVAS.T_PAQUETE (CODPYTO, CODENTREGABLE, CODPAQUETE) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

---- ÍNDICE T_CAT_VIDEO_PK
CREATE UNIQUE INDEX SYSCANVAS.T_CAT_VIDEO_PK ON SYSCANVAS.T_CAT_VIDEO (CODPYTO, CODRUTAPY, NROVERSION, COD_VIDEO) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

COMMIT;

---- ÍNDICE CODPYTO__UN
CREATE UNIQUE INDEX SYSCANVAS.CODPYTO__UN ON SYSCANVAS.T_CONVOCATORIA (CODPYTO) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

---- ÍNDICE T_CONVOCATORIA_PK
CREATE UNIQUE INDEX SYSCANVAS.T_CONVOCATORIA_PK ON SYSCANVAS.T_CONVOCATORIA (NROCONV) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

---- ÍNDICE T_EMPRESA_PK
CREATE UNIQUE INDEX SYSCANVAS.T_EMPRESA_PK ON SYSCANVAS.T_EMPRESA (CODPERSONA) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

---- ÍNDICE T_PERSPROFESION_PK
CREATE UNIQUE INDEX SYSCANVAS.T_PERSPROFESION_PK ON SYSCANVAS.T_PERSPROFESION (CODPERS, CORRPROF) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ;

--- ÍNDICE T_CAT_FOTO_PK
CREATE UNIQUE INDEX SYSCANVAS.T_CAT_FOTO_PK ON SYSCANVAS.T_CAT_FOTO (CODPYTO, CODRUTAPY, NROVERSION, COD_FOTO) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

COMMIT;

---- ÍNDICE T_PARTIDAING_PK
CREATE UNIQUE INDEX SYSCANVAS.T_PARTIDAING_PK ON SYSCANVAS.T_PARTIDAING (INGEGR, CODPARTIDAI) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

--- ÍNDICE T_PRESINGRESO_PK
CREATE UNIQUE INDEX SYSCANVAS.T_PRESINGRESO_PK ON SYSCANVAS.T_PRESINGRESO (CODPYTO, NROVERSION) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

--- ÍNDICE T_PYTOHITOS_PK
CREATE UNIQUE INDEX SYSCANVAS.T_PYTOHITOS_PK ON SYSCANVAS.T_PYTOHITOS (CODPYTO) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ;

--- ÍNDICE T_HITOSCONV_PK
CREATE UNIQUE INDEX SYSCANVAS.T_HITOSCONV_PK ON SYSCANVAS.T_HITOSCONV (CODHITO) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

--- ÍNDICE T_TIPOPAVIMENTO_PK
CREATE UNIQUE INDEX SYSCANVAS.T_TIPOPAVIMENTO_PK ON SYSCANVAS.T_TIPOPAVIMENTO (TIPPAV) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

COMMIT;

--- ÍNDICE T_FUNCION_PK
CREATE UNIQUE INDEX SYSCANVAS.T_FUNCION_PK ON SYSCANVAS.T_FUNCION (CODFUNCION) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

--- ÍNDICE T_PYTOPERS_PK
CREATE UNIQUE INDEX SYSCANVAS.T_PYTOPERS_PK ON SYSCANVAS.T_PYTOPERS (CODPYTO, CORREMPL) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

--- ÍNDICE T_PROFESIONES_PK
CREATE UNIQUE INDEX SYSCANVAS.T_PROFESIONES_PK ON SYSCANVAS.T_PROFESIONES (CODPROF) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

--- ÍNDICE T_FASE_PK
CREATE UNIQUE INDEX SYSCANVAS.T_FASE_PK ON SYSCANVAS.T_FASE (CODFASE) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

COMMIT;

--- ÍNDICE T_CARGO_PK
CREATE UNIQUE INDEX SYSCANVAS.T_CARGO_PK ON SYSCANVAS.T_CARGO (CODCARGO) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

--- ÍNDICE T_CRITERIO_TRAMIF_PK
CREATE UNIQUE INDEX SYSCANVAS.T_CRITERIO_TRAMIF_PK ON SYSCANVAS.T_CRITERIO_TRAMIF (CODCRITERIO) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

--- ÍNDICE T_ENTREGABLE_PK
CREATE UNIQUE INDEX SYSCANVAS.T_ENTREGABLE_PK ON SYSCANVAS.T_ENTREGABLE (CODPYTO, CODENTREGABLE) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

--- ÍNDICE T_DEPARTAMENTO_PK
CREATE UNIQUE INDEX SYSCANVAS.T_DEPARTAMENTO_PK ON SYSCANVAS.T_DEPARTAMENTO (CODDPTO) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

--- ÍNDICE T_CAPACITACION_PK
CREATE UNIQUE INDEX SYSCANVAS.T_CAPACITACION_PK ON SYSCANVAS.T_CAPACITACION (CODPERS, CORRCAP) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ;

COMMIT;

--- ÍNDICE T_PARTIDAEGR_1_PK
CREATE UNIQUE INDEX SYSCANVAS.T_PARTIDAEGR_1_PK ON SYSCANVAS.T_PARTIDAEGR_1 (IDCC) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ;

--- ÍNDICE T_SITUACION_PK
CREATE UNIQUE INDEX SYSCANVAS.T_SITUACION_PK ON SYSCANVAS.T_SITUACION (CODFASE, CODNIVEL, CODSITUACION) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

--- ÍNDICE T_PROVINCIA_PK
CREATE UNIQUE INDEX SYSCANVAS.T_PROVINCIA_PK ON SYSCANVAS.T_PROVINCIA (CODDPTO, CODPROV) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

--- ÍNDICE T_PERSONA_PK
CREATE UNIQUE INDEX SYSCANVAS.T_PERSONA_PK ON SYSCANVAS.T_PERSONA (CODPERSONA) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

---- ÍNDICE T_TIPO_DOC_PK
CREATE UNIQUE INDEX SYSCANVAS.T_TIPO_DOC_PK ON SYSCANVAS.T_TIPO_DOC (TIPDOC) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

---- ÍNDICE T_TRAMO_GPS_PREL_PK
CREATE UNIQUE INDEX SYSCANVAS.T_TRAMO_GPS_PREL_PK ON SYSCANVAS.T_TRAMO_GPS_PREL (CODPYTO, CODRUTA, CODTRAMO, CODVERSION, CORREL) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ;

---- ÍNDICE T_TRAMO_VIDEOF_PK
CREATE UNIQUE INDEX SYSCANVAS.T_TRAMO_VIDEOF_PK ON SYSCANVAS.T_TRAMO_VIDEOF (CODPYTO, CODRUTAPY, CODTRAMOPY, NROVERSION, CORREL) 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ;

COMMIT;