-- =====================================================================
-- SCRIPT PARA LA ELIMINACIÓN COMPLETA DE OBJETOS DEL ESQUEMA SYSCANVAS
-- Ejecutar este script borrará de forma permanente todos los objetos listados.
-- =====================================================================

-- 1. Eliminación de Triggers
-- Se eliminan primero para evitar que se disparen durante el borrado de tablas.
-- =====================================================================
DROP TRIGGER "T_DOCUMENTO_TRG";
DROP TRIGGER "T_ENTREGABLE_TRG";
DROP TRIGGER "T_PAQUETE_TRG";
DROP TRIGGER "TRIGUNO";

-- 2. Eliminación de Procedimientos Almacenados
-- =====================================================================
DROP PROCEDURE "CRUDTRAMO";
DROP PROCEDURE "DELETERUTA";
DROP PROCEDURE "INSERTSUBTRAMO";
DROP PROCEDURE "INSERTTRAMO";
DROP PROCEDURE "RUTAVER2";
DROP PROCEDURE "SP_ACTUALIZAR_EXPERIENCIA";
DROP PROCEDURE "SP_AGREGAR_EXPERIENCIA";
DROP PROCEDURE "SP_AGREGAR_PROVINCIA";
DROP PROCEDURE "SP_CRUD_PYTOPERS";
DROP PROCEDURE "SP_ELIMINAR_EXPERIENCIA";
DROP PROCEDURE "UPDATERUTA";
DROP PROCEDURE "UPDATESUBTRAMO";
DROP PROCEDURE "UPDATETRAMO";
DROP PROCEDURE "UP_PRES_ELIMINARPARTIDA";

-- 3. Eliminación de Secuencias
-- =====================================================================
DROP SEQUENCE "ISECUNO";
DROP SEQUENCE "SC_CANVAS_SEQ";
DROP SEQUENCE "T_DOCUMENTO_SEQ";
DROP SEQUENCE "T_ENTREGABLE_SEQ";
DROP SEQUENCE "T_PAQUETE_SEQ";

-- 4. Eliminación de Tablas
-- La opción CASCADE CONSTRAINTS elimina automáticamente las foreign keys
-- y otras dependencias, asegurando un borrado limpio.
-- =====================================================================
DROP TABLE "SC_CANVAS" CASCADE CONSTRAINTS;
DROP TABLE "SC_CARGO" CASCADE CONSTRAINTS;
DROP TABLE "SC_COMENTARIO" CASCADE CONSTRAINTS;
DROP TABLE "SC_ESTADO" CASCADE CONSTRAINTS;
DROP TABLE "SC_ETAPA" CASCADE CONSTRAINTS;
DROP TABLE "SC_HISTORIAL" CASCADE CONSTRAINTS;
DROP TABLE "SC_TAREA" CASCADE CONSTRAINTS;
DROP TABLE "SC_TIPO_CANVAS" CASCADE CONSTRAINTS;
DROP TABLE "T_ASEGURADORA" CASCADE CONSTRAINTS;
DROP TABLE "T_CAPACITACION" CASCADE CONSTRAINTS;
DROP TABLE "T_CARGO" CASCADE CONSTRAINTS;
DROP TABLE "T_CAT_FOTO" CASCADE CONSTRAINTS;
DROP TABLE "T_CAT_VIDEO" CASCADE CONSTRAINTS;
DROP TABLE "T_CENTROESTUDIO" CASCADE CONSTRAINTS;
DROP TABLE "T_CLIENTE" CASCADE CONSTRAINTS;
DROP TABLE "T_CONTRATO" CASCADE CONSTRAINTS;
DROP TABLE "T_CONVOCATORIA" CASCADE CONSTRAINTS;
DROP TABLE "T_CONV_FECHAS" CASCADE CONSTRAINTS;
DROP TABLE "T_CRITERIO_TRAMIF" CASCADE CONSTRAINTS;
DROP TABLE "T_DEPARTAMENTO" CASCADE CONSTRAINTS;
DROP TABLE "T_DISTRITO" CASCADE CONSTRAINTS;
DROP TABLE "T_DOCUMENTO" CASCADE CONSTRAINTS;
DROP TABLE "T_EMPLEADO" CASCADE CONSTRAINTS;
DROP TABLE "T_EMPRESA" CASCADE CONSTRAINTS;
DROP TABLE "T_ENTREGABLE" CASCADE CONSTRAINTS;
DROP TABLE "T_ESTADO" CASCADE CONSTRAINTS;
DROP TABLE "T_EXPERIENCIA" CASCADE CONSTRAINTS;
DROP TABLE "T_FASE" CASCADE CONSTRAINTS;
DROP TABLE "T_FLUJOCAJA" CASCADE CONSTRAINTS;
DROP TABLE "T_FLUJOCAJA_DET" CASCADE CONSTRAINTS;
DROP TABLE "T_FUNCION" CASCADE CONSTRAINTS;
DROP TABLE "T_GPS_PYTO" CASCADE CONSTRAINTS;
DROP TABLE "T_GRADO" CASCADE CONSTRAINTS;
DROP TABLE "T_HITOSCONV" CASCADE CONSTRAINTS;
DROP TABLE "T_INGEGRESO_DET" CASCADE CONSTRAINTS;
DROP TABLE "T_ING_EGRESO" CASCADE CONSTRAINTS;
DROP TABLE "T_MONEDA" CASCADE CONSTRAINTS;
DROP TABLE "T_NIVEL" CASCADE CONSTRAINTS;
DROP TABLE "T_OBJCONTRAT" CASCADE CONSTRAINTS;
DROP TABLE "T_PAQUETE" CASCADE CONSTRAINTS;
DROP TABLE "T_PARTIDAEGR_1" CASCADE CONSTRAINTS;
DROP TABLE "T_PARTIDAING" CASCADE CONSTRAINTS;
DROP TABLE "T_PERSONA" CASCADE CONSTRAINTS;
DROP TABLE "T_PERSPROFESION" CASCADE CONSTRAINTS;
DROP TABLE "T_PRESINGRESO" CASCADE CONSTRAINTS;
DROP TABLE "T_PRESINGRESO_DET" CASCADE CONSTRAINTS;
DROP TABLE "T_PROFESIONES" CASCADE CONSTRAINTS;
DROP TABLE "T_PROVINCIA" CASCADE CONSTRAINTS;
DROP TABLE "T_PROYECTO" CASCADE CONSTRAINTS;
DROP TABLE "T_PYTOCLIENTESP" CASCADE CONSTRAINTS;
DROP TABLE "T_PYTOHITOS" CASCADE CONSTRAINTS;
DROP TABLE "T_PYTOPERS" CASCADE CONSTRAINTS;
DROP TABLE "T_RESULCONV" CASCADE CONSTRAINTS;
DROP TABLE "T_RUTA" CASCADE CONSTRAINTS;
DROP TABLE "T_SITUACION" CASCADE CONSTRAINTS;
DROP TABLE "T_SUBTRAMO" CASCADE CONSTRAINTS;
DROP TABLE "T_TAXONOMIA" CASCADE CONSTRAINTS;
DROP TABLE "T_TIPOINTERVENC" CASCADE CONSTRAINTS;
DROP TABLE "T_TIPOPAVIMENTO" CASCADE CONSTRAINTS;
DROP TABLE "T_TIPO_CP" CASCADE CONSTRAINTS;
DROP TABLE "T_TIPO_DOC" CASCADE CONSTRAINTS;
DROP TABLE "T_TIPO_PERSONA" CASCADE CONSTRAINTS;
DROP TABLE "T_TRAMO" CASCADE CONSTRAINTS;
DROP TABLE "T_TRAMO_GPS_PREL" CASCADE CONSTRAINTS;
DROP TABLE "T_TRAMO_VIDEODET" CASCADE CONSTRAINTS;
DROP TABLE "T_TRAMO_VIDEOF" CASCADE CONSTRAINTS;
DROP TABLE "T_TRAMO_VIDEOF_PREL" CASCADE CONSTRAINTS;

-- 5. Limpieza de la Papelera de Reciclaje (Opcional pero recomendado)
-- Este comando asegura que los objetos se eliminen permanentemente.
-- =====================================================================
PURGE RECYCLEBIN;

-- Fin del script. El esquema debería estar vacío.