---  TRIGGER T_DOCUMENTO_TRG
CREATE OR REPLACE NONEDITIONABLE TRIGGER SYSCANVAS.T_DOCUMENTO_TRG 
    BEFORE INSERT ON T_DOCUMENTO 
    FOR EACH ROW 
    BEGIN
    <<COLUMN_SEQUENCES>>
    BEGIN
        IF INSERTING AND :NEW.CODDOC IS NULL THEN
        SELECT T_DOCUMENTO_SEQ.NEXTVAL INTO :NEW.CODDOC FROM SYS.DUAL;
        END IF;
    END COLUMN_SEQUENCES;
    END;
/
ALTER TRIGGER SYSCANVAS.T_DOCUMENTO_TRG ENABLE;

---  TRIGGER T_ENTREGABLE_TRG
CREATE OR REPLACE NONEDITIONABLE TRIGGER SYSCANVAS.T_ENTREGABLE_TRG 
    BEFORE INSERT ON T_ENTREGABLE 
    FOR EACH ROW 
    BEGIN
    <<COLUMN_SEQUENCES>>
    BEGIN
        IF INSERTING AND :NEW.CODENTREGABLE IS NULL THEN
        SELECT T_ENTREGABLE_SEQ.NEXTVAL INTO :NEW.CODENTREGABLE FROM SYS.DUAL;
        END IF;
    END COLUMN_SEQUENCES;
    END;
/
ALTER TRIGGER SYSCANVAS.T_ENTREGABLE_TRG ENABLE;

---  TRIGGER T_PAQUETE_TRG
CREATE OR REPLACE NONEDITIONABLE TRIGGER SYSCANVAS.T_PAQUETE_TRG 
    BEFORE INSERT ON T_PAQUETE 
    FOR EACH ROW 
    BEGIN
    <<COLUMN_SEQUENCES>>
    BEGIN
        IF INSERTING AND :NEW.CODPAQUETE IS NULL THEN
        SELECT T_PAQUETE_SEQ.NEXTVAL INTO :NEW.CODPAQUETE FROM SYS.DUAL;
        END IF;
    END COLUMN_SEQUENCES;
    END;
/
ALTER TRIGGER SYSCANVAS.T_PAQUETE_TRG ENABLE;

---  TRIGGER TRIGUNO
CREATE OR REPLACE NONEDITIONABLE TRIGGER SYSCANVAS.TRIGUNO 
    BEFORE INSERT ON T_RESULCONV
    for EACH ROW
    BEGIN
    SELECT isecuno.NEXTVAL INTO :NEW.CORRCONV from DUAL;
    END; 
    /
ALTER TRIGGER SYSCANVAS.TRIGUNO ENABLE;
