/*COSAS A AUMENTAR EN LOS SCRIPTS*/

INSERT INTO SYSCANVAS.SC_TIPO_CANVAS (TIPCANVAS, DESTIPCANVAS, VIGENTE)
SELECT 'F', 'Canvas Libre', 1 FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM SYSCANVAS.SC_TIPO_CANVAS WHERE TIPCANVAS = 'F'
);

COMMIT;

ALTER TABLE SC_CANVAS
MODIFY (CODPYTO NULL);

SELECT column_name FROM user_tab_columns
WHERE table_name = 'SC_CANVAS' AND column_name = 'CODCREADOR';


CREATE SEQUENCE SC_HISTORIAL_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;


ALTER TABLE SC_CANVAS ADD CODCREADOR NUMBER(6);


UPDATE SC_CANVAS SET CODCREADOR = CODPERSONA WHERE CODCREADOR IS NULL;


ALTER TABLE SYSCANVAS.SC_CANVAS
MODIFY (CODPERSONA NULL);


ALTER TABLE SYSCANVAS.SC_CANVAS
MODIFY (CODPYTO NULL);


COMMIT;
